<h1><center>  Lab 1 – Basic NumPy Operations<center</h1>
<h6>Submitted by Beena Kurian(8946601)</h6>
<b>PART - A</b>
<b> Notebook to demonstrate NumPy Operations </b>

<font color="blue"><b>1. Create an array that starts from the integer 1, ends at 20, incremented by 3.</b></font>

In [31]:
import numpy as np
A=np.arange(1,20,3)
print(a)

[ 1  4  7 10 13 16 19]


<font color="blue"><b>2. Create a new array of shape 3 with random numbers between 0 and 1.<b></font>

In [32]:
B = []
for i in range(3):
    B.append(np.random.rand())
print("random numbers between 0 and 1\n",B)

random numbers between 0 and 1
 [0.8900666813944441, 0.10279941941346715, 0.42653729435073295]


<font color="blue"><b>3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.<b></font>

In [33]:
C=np.array([[10,20,45], [30,12,16], [42,17,56]])
print("first 2 Rows\n",C[0:2])
print("Last 2 Rows\n",C[1:3])

first 2 Rows
 [[10 20 45]
 [30 12 16]]
Last 2 Rows
 [[30 12 16]
 [42 17 56]]


<font color="blue"><b>4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:<b></font>

In [34]:
D=np.array([[10,20,30], [40,50,60]])
E=np.array([[70,80,90], [100,110,120]])

print("Stack the elements vertically\n",np.vstack((D,E)))
print("Stack the elements horizontally\n",np.hstack((D,E)))
print("splitting the arrays using array split\n",np.array_split(D,3))
print("splitting the arrays \n",np.hsplit(D,3))


Stack the elements vertically
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Stack the elements horizontally
 [[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]
splitting the arrays using array split
 [array([[10, 20, 30]]), array([[40, 50, 60]]), array([], shape=(0, 3), dtype=int32)]
splitting the arrays 
 [array([[10],
       [40]]), array([[20],
       [50]]), array([[30],
       [60]])]


<font color="blue"><b> 5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
<br>
 Is it possible to multiply these matrices?</font>
<br>ANS: A matrix of shape (m, n) can be multiplied with a matrix of size (p,q) if and only if n is equal to p, then the shape of the resultant matrix will be (m,q). In the given example X is a matrix of shape (3,3) and Y is of shape (3,2), Thus, number of columns of first matrix is equal to number of rows of the second matrix. Thus it is possible to multiply x with Y. The resultant matrix will be of size (3,2). But the reverse is not possible. That is Y with X.<br>
<font color="blue">Demonstrate the case when it is not possible to.<b></font>
<br> When we try to multiply Y with X, we can't multiply. Both examples are demonstrated below.


In [40]:
X=np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y=np.array([[4, 2], [6, 2], [4, 2]])

print("Trying to multiply X * Y -\n",np.dot(X,Y))
try:
    print("Trying to multiply Y * X -\n",np.dot(Y,X))
except:
    print("Not possible to multiply Y * X- The column of first matrix is not equal to second")


Trying to multiply X * Y -
 [[70 28]
 [70 30]
 [60 26]]
Not possible to multiply Y * X- The column of first matrix is not equal to second


<font color="blue"><b>6. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).</b>,</font>

In [49]:
X=np.array([2, -1, -8])
print("shape of X=",X.shape)
print("Dimension of vector X=",X.ndim)
Y=np.array([3, 1, -2])
print("shape of X=",Y.shape)


shape of X= (3,)
Dimension of vector X= 1
shape of X= (3,)


7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.