<h1><center>  Lab 1 – Basic NumPy Operations<center</h1>
<h6>Submitted by Beena Kurian(8946601)</h6>


<b>PART - A</b>
<b> Notebook to demonstrate NumPy Operations </b>

<font color="blue"><b>1. Create an array that starts from the integer 1, ends at 20, incremented by 3.</b></font>

In [1]:
import numpy as np
A=np.arange(1,20,3)
print("An array 1-20 incremented by:", A)

An array 1-20 incremented by: [ 1  4  7 10 13 16 19]


<font color="blue"><b>2. Create a new array of shape 3 with random numbers between 0 and 1.<b></font>

In [2]:
B=np.random.rand(3)
print(B)

[0.4645874  0.22024276 0.14474393]


<font color="blue"><b>3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.<b></font>

In [3]:
# Creating Arrays
C=np.array([[10,20,45], [30,12,16], [42,17,56]])

# Slicing Arrays
print("first 2 Rows\n",C[:2])
print("Last 2 Rows\n",C[-2:])

first 2 Rows
 [[10 20 45]
 [30 12 16]]
Last 2 Rows
 [[30 12 16]
 [42 17 56]]


<font color="blue"><b>4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
<b></font>

In [4]:
# Creating Arrays
D=np.array([[10,20,30], [40,50,60]])
E=np.array([[70,80,90], [100,110,120]])

# Array Stacking
print("Stack the elements vertically\n",np.vstack((D,E)))
print("Stack the elements horizontally\n",np.hstack((D,E)))

# Array split, Vertical and Horizontal Split
print("splitting the arrays using array split\n",np.array_split(D,2))
print("splitting the arrays horizontally \n",np.hsplit(D,3))
print("splitting the arrays vertically\n",np.vsplit(D,1))

Stack the elements vertically
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Stack the elements horizontally
 [[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]
splitting the arrays using array split
 [array([[10, 20, 30]]), array([[40, 50, 60]])]
splitting the arrays horizontally 
 [array([[10],
       [40]]), array([[20],
       [50]]), array([[30],
       [60]])]
splitting the arrays vertically
 [array([[10, 20, 30],
       [40, 50, 60]])]


<font color="blue"><b> 5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
Is it possible to multiply these matrices?</font>
<br>ANS: A matrix of shape (m, n) can be multiplied with a matrix of size (p,q) if and only if n is equal to p, then the shape of the resultant matrix will be (m,q). In the given example X is a matrix of shape (3,3) and Y is of shape (3,2), Thus, number of columns of first matrix is equal to number of rows of the second matrix. Thus it is possible to multiply x with Y. The resultant matrix will be of size (3,2). But the reverse is not possible. That is Y with X.<br>
<font color="blue">Demonstrate the case when it is not possible to.<b></font>
<br> When we try to multiply Y with X, we can't multiply. Both examples are demonstrated below.</b>


In [5]:
# Creating 2 Matrices
X=np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y=np.array([[4, 2], [6, 2], [4, 2]])

# Multiplying X*Y
if(X.shape[1]==Y.shape[0]):
    print(" ----------X * Y ----------- \n",np.matmul(X,Y))
else:
    print("OOPs...!!!! Not possible to multiply X * Y")
    print("The number of columns of first matrix is not equal to the row of second matrix")
    
# Multiplying Y*X
if(Y.shape[1]==X.shape[0]):
    print(" ----------Y * X ----------- \n",np.matmul(Y,X))
else:
    print("\nOOPs...!!!! Not possible to multiply Y * X")
    print("The number of columns of first matrix is not equal to the row of second matrix")


 ----------X * Y ----------- 
 [[70 28]
 [70 30]
 [60 26]]

OOPs...!!!! Not possible to multiply Y * X
The number of columns of first matrix is not equal to the row of second matrix


<font color="blue"><b>6. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]),
Find the Shape, Number of dimensions of vector x.<br>
Reshape the vector x to a matrix of size (3,1) and <br>determine the number of dimensions after reshaping y to a matrix of (3,1).</b>,</font>

In [6]:
# Creating Arrays
X=np.array([2, -1, -8])
Y=np.array([3, 1, -2])

# Shape of Arrays
print("Shape of vector X=",X.shape)
print("Shape of vector Y=",Y.shape)

# Dimension of Array X
print("Dimension of vector X=",X.ndim)

# Reshaping of Array X and check shape again
X_new=X.reshape(3,1)
print("Reshaping array X to (3,1)\n",X_new)
print("Shape of reshaped vector X=",X_new.shape)

# Reshaping of Array Y and check shape again
Y_new=Y.reshape(3,1)
print("Dimension of reshaped Y=",Y_new.ndim)
print("Shape of reshaped vector Y=",Y_new.shape)


Shape of vector X= (3,)
Shape of vector Y= (3,)
Dimension of vector X= 1
Reshaping array X to (3,1)
 [[ 2]
 [-1]
 [-8]]
Shape of reshaped vector X= (3, 1)
Dimension of reshaped Y= 2
Shape of reshaped vector Y= (3, 1)


<font color="blue"><b>7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.</b></font>
<br><b>Broadcasting is the ability of Numpy to treat arrays of different shapes to perform arithemetic operations. <br>The shape of the arrays are compatible if they are of same size or one of then is of size one.

In [7]:
# Creating Arrays
A=np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
B=np.array([2])
C=np.array([[5, 7, 2], [4, 5, 6], [1, 1 ,1]])

# Broadcast Examples
DEC1=A-B
print("Subtraction using broadcasting\n",DEC1)
DEC2=A-C
print("Subtraction using broadcasting\n",DEC2)
MUL1=A*B
print("Multiplication using broadcasting\n",MUL1)
MUL2=A*C
print("Multiplication using broadcasting\n",MUL2)



Subtraction using broadcasting
 [[3 5 0]
 [2 3 4]
 [5 2 0]]
Subtraction using broadcasting
 [[0 0 0]
 [0 0 0]
 [6 3 1]]
Multiplication using broadcasting
 [[10 14  4]
 [ 8 10 12]
 [14  8  4]]
Multiplication using broadcasting
 [[25 49  4]
 [16 25 36]
 [ 7  4  2]]


<center><b>PART - B
Linear Equations </b></center>

<font color="Blue"><b>Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using numpy functions.</b></font><br>




<b>Part B.1</b><br>
4x + y - 2z = 10<br>
2x - 3y + 2z = -4<br>
x + 2y + 3z = 6<br>
<b>Expected solution: The determinant of the matrix is not zero, thus, the matrix is non-singular,and  we can solve the matrix. This equations can be solved by numpy function np.linalg.solve()</b> 

In [8]:
# Representing Linear Equations 
L=np.array([[4,1,-2],[2,-3,2],[1,2,3]])
R=np.array([10,-4,6])

# computing determinant of matrix L
detL=np.linalg.det(L)

# Expected Solution
print("------------Expected Solution-------------------:")
if(detL==0):
    print("Singular, Not solvable")
else:
    print("Non-singular, solvable")

#trying to solve linear equations using numpy function
print("------------Actual Solution------------:")
try: 
    result=np.linalg.solve(L,R)            
    print("Part B.1, Solution = ", result)
except:
    print("Sorry...!!! The linear system of equations is not solvable using numpy function because determinant=",detL)


------------Expected Solution-------------------:
Non-singular, solvable
------------Actual Solution------------:
Part B.1, Solution =  [ 1.8  2.4 -0.2]


<b>Part B.2</b><br>
2x - y + 3z + 4w = 10<br>
4x - 2y + 6z + 8w = 20<br>
3x + y - 2z + 2w = 3<br>
x + 3y - 4z + w = -1<br>
<b>Expected solution: The determinant of the matrix is zero, thus, the matrix is singular,and  we can not solve the matrix</b> 

In [9]:
L=np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]])
R=np.array([10,20,3,-1])

# computing determinant of matrix L
detL=np.linalg.det(L)

# Expected Solution
print("------------Expected Solution-------------------:")
if(detL==0):
    print("Singular, Not solvable")
else:
    print("Non-singular, solvable")

#trying to solve linear equations using numpy function
print("---------------Actual Solution------------------:")
try: 
    result=np.linalg.solve(L,R)            
    print("Part B.2, Solution = ", result)
except:
    print("Sorry...!!! The linear system of equations is not solvable using numpy function because determinant=",detL)

------------Expected Solution-------------------:
Singular, Not solvable
---------------Actual Solution------------------:
Sorry...!!! The linear system of equations is not solvable using numpy function because determinant= 0.0
